[package]
name = "dtls"
version = "0.1.0"
authors = ["smb123"]
edition = "2018"
description = "Library for working with Smash 4 DTLS Extration"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "dtls"
path = "src/main.rs"


[dependencies]
binread = "2.1.1"
flate2 = "1.0.20"
crc32fast = "1.2"

